version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:6.13
    steps:
      - checkout
      - run:
          command: |
            cd lib
            npm install
            npm run lint
  test:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - run:
          command: |
            npm install
            set +e
            npm run sample-test
            npm run sample-test-hierarchy
            npm test
workflows:
  version: 2
  work-it:
    jobs:
      - lint
      - test
